#!/usr/bin/env python3
"""Rewrite a possibly-malformed .env into a bash-source-safe form.

Root cause fix for the 2026-07-16/17/18 secret-exposure incidents: a raw
`source .env` in bash aborts (under set -e) on any line bash can't parse
as an assignment, and bash's own "command not found" error embeds the
offending line's content verbatim -- including secret values -- in
whatever captures stderr. This script never prints a value anywhere. It
only reads KEY=VALUE pairs with Python's own parser (which doesn't choke
the way bash's word-splitting does) and re-emits each one with guaranteed
-safe single-quoting, so the file downstream scripts source can never
throw a parse error. Malformed lines are silently skipped and reported
only by line number and variable-name-shape, never by content.
"""
import re
import sys

LINE_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$")


def parse_line(line):
    stripped = line.rstrip("\n")
    if not stripped.strip() or stripped.strip().startswith("#"):
        return None
    m = LINE_RE.match(stripped)
    if not m:
        return None
    key, val = m.group(1), m.group(2)
    if len(val) >= 2 and val[0] == val[-1] and val[0] in ("'", '"'):
        val = val[1:-1]
    return key, val


def main():
    if len(sys.argv) != 3:
        print("usage: sanitize_env.py <src .env> <dst safe-env>", file=sys.stderr)
        return 2
    src, dst = sys.argv[1], sys.argv[2]
    written = 0
    skipped_lines = []
    with open(src) as f, open(dst, "w") as out:
        out.write("# AUTO-GENERATED by sanitize_env.py -- do not edit directly.\n")
        out.write("# Regenerated from .env each run. Guaranteed source-safe quoting.\n")
        for i, line in enumerate(f, 1):
            parsed = parse_line(line)
            if parsed is None:
                if line.strip() and not line.strip().startswith("#"):
                    skipped_lines.append(i)
                continue
            key, val = parsed
            safe_val = "'" + val.replace("'", "'\\''") + "'"
            out.write(f"export {key}={safe_val}\n")
            written += 1
    print(f"sanitize_env: {written} vars written to {dst}", file=sys.stderr)
    if skipped_lines:
        print(
            f"sanitize_env: WARNING skipped malformed line(s) {skipped_lines} "
            "in source .env -- fix in your own editor, content never printed",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
